name: macos

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and test ${{matrix.build-type}} mode
    runs-on: macos-latest
    strategy:
      matrix:
        build-type: [Debug, Release]

    steps:
      - name: Clone recursively
        uses: actions/checkout@v3
        with:
          submodules: recursive


      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            ./llvm
          key: llvm-16
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: 16
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
          env: true

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DBUILD_TESTING=ON -DFE_BUILD_EXAMPLES=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build -v

#     - name: Test
#       working-directory: ${{github.workspace}}/build
#       run: |
#         export PATH=${{github.workspace}}/bin:$PATH
#         ctest --verbose -C ${{matrix.build-type}} --output-on-failure
